### ISSUE TITLE
ASP.NET-Core-2 NLog setup question

### ISSUE THREAD

**Issue by arsanov** [NLog/NLog.Web#506] opened 2019-11-06 14:11 UTC
Hi,

I've read [this guide ](https://github.com/NLog/NLog/wiki/Getting-started-with-ASP.NET-Core-2) and noticed that with this approach NLog is registered as a ILoggerProvider, not a ILoggerFactory. And the existing functionality of Microsoft ILoggerFactory implementation is used, which creates logger providers. 

The question is why not registering just ILoggerFactory and ILogger implementations of NLog? Using the approach from the guide the configuration is spread between two different config files. 

Is there any advantage using ILoggerProvider and Microsoft LoggerFactory over NLog logger factory(nlog package contains the implementations of ILogger and ILoggerFactory)?

**Comment by snakefoot** [comment] 2019-11-06 19:06
@arsanov You are welcome to create a PullRequest to resolve #235 that adds a new option for:

https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/Logging/NLogProviderOptions.cs

That causes AddNLog / UseNLog to replace the existing LoggerFactory with this one:

https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/Logging/NLogLoggerFactory.cs

**Comment by arsanov** [comment] 2019-11-07 10:35
> > The question is why not registering just ILoggerFactory and ILogger implementations of NLog?
> 
> You will lose the default stuff (console target etc) of Microsoft and that was confusing before.
> See #235

Yes, I saw an issue that someone was using AddConsole while configuring dotnet core host builder and after UseNlog it didn't log anything to console.

For me this is complete opposite - it would be unexpected if I set up using NLog as a logger for my application and suddenly I start getting message in console, although it is not set up in NLog config.

In our project we used NLog directly(i.e. using NLog's ILogger interface) and then decided to switch to Microsoft ILogger - it would help us a lot with external libraries which use Microsoft ILogger interface.

But obiously we didn't wan't to use another logger since we're happy with NLog, the idea was just to change from NLog ILogger to Microsoft ILogger interface. I.e. we already have all nlog settings set up in config. So I would not ever expect appsettings affecting any kind of logger settings, I would like to avoid any kind of mixing things together, but at the moment it is so - we have settings in nlog config but also we have settings in appsettings. 

But then I started thinking about why would one use nlog as a logger provider not a complete logging framework. And I can imagine it - say we're absolutely happy with Microsoft logger, but we need one more thing which is not supported there, while it is supported by NLog. Then the solution would be really just adding NLog as a provider.

But those are just two different cases - adding as a logger provider or registering as a logging framework.
I.e. if I configure logger with AddConsole, AddWhatEver, then I would expect registering NLog with something like AddNlog.
And it works that way - there is already AddNlog method which registers NLog as a provider.

But if I use NLog as a framework then I would expect something like UseNlog which registers ILogger, ILoggerFactory, ILoggerProvider implementations and then NLog is used everywhere, and no confusion between configs - unlike now.

And I would not understand someone expecting AddConsole still works with UseNlog(like #199) - why not using AddNlog of ILoggerBuilder then? To avoid that optionally NLog Factory could throw an exception when someone tries to add logger provider.

**Comment by snakefoot** [comment] 2019-11-07 17:11
@arsanov All your observations are valid. But `UseNLog()` is already in production. Changing its behavior so it behaves very different would require a major version. And also more than 1-2 people should be fighting for this change in behavior (Since it will generate a lot of downstream work for all consuming applications).

But you are very welcome to create a pull-request that implements a new option-property for using NLog LoggerFactory (as suggested in my previous comment)

**Comment by snakefoot** [comment] 2019-11-15 17:37
@arsanov Can this be closed as a duplicate of #192 ?

**Comment by arsanov** [comment] 2019-11-15 17:41
@snakefoot Yes, please close this and  I'll try to create pull request for #192

**Closed** 2019-11-15 17:49 UTC
