### ISSUE TITLE
${aspnet-request} empty log

### ISSUE THREAD

**Issue by Tabgyn** [NLog/NLog.Web#583] opened 2020-06-19 14:40 UTC
**Type**:

- Bug

**NLog version**: 4.7.2

**NLog.Web version**: 4.9.2

**Platform**: .Net 4.5

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwConfigExceptions="true">
  <targets>
    <target name="logfile" xsi:type="File" fileName="file.txt" layout="${aspnet-request}"/>    
  </targets>

  <rules>
    <logger name="*" minlevel="Error" writeTo="logfile"/>
  </rules>
</nlog>
```

**C# Controller**

```c#
using NLog;
using System;
using System.Web.Mvc;

namespace NLogSample.Controllers
{
    public class HomeController : Controller
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }

        public ActionResult Exception(string value, string body)
        {
            try
            {
                if(string.IsNullOrEmpty(value))
                    throw new ArgumentNullException(nameof(value));
            }
            catch (Exception ex)
            {
                Logger.Error(ex, ex.Message);
                throw;
            }

            return RedirectToAction("Index");
        }
    }
}
```

- What is the current result?
${aspnet-request} logs nothing

- What is the expected result?
Request to be logged

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Yes. The internal log does not have errors.

- Please post full exception details (message, stacktrace, inner exceptions)
```
Value cannot be null.
Parameter name: value
   at NLogSample.Controllers.HomeController.Exception(String value, String body) in C:\Users\Tiago\source\repos\NLogSample\NLogSample\Controllers\HomeController.cs:line 30
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()

```

- Are there any workarounds? 
No

**Comment by snakefoot** [comment] 2020-06-21 11:57
The documentation says that you need to specify what part of the AspNet-Request-HttpContext that you want to output (cookie, header, item, form, queryString):

https://github.com/NLog/NLog/wiki/AspNetRequest-layout-renderer

You will also notice that for ASP.NET Core, then it has been split into several [layoutrenderers](https://nlog-project.org/config/?tab=layout-renderers&search=package:nlog.web.aspnetcore).

Maybe try this instead:

`layout="${aspnet-request-url:includeQueryString=true}`

See also: https://github.com/NLog/NLog/wiki/AspNetRequest-Url-Layout-Renderer

**Comment by Tabgyn** [comment] 2020-06-26 19:51
Thank you! But now I'm trying to use `${aspnet-request-posted-body}` and it doesn't show anything".

**Comment by snakefoot** [comment] 2020-06-26 21:13
Sounds like a different issue. Maybe duplicate of #556

**Comment by Tabgyn** [comment] 2020-06-29 17:45
I saw this issue, trying to work on a workaround since in my case it is Framework 4.5 and not Core

**Comment by snakefoot** [comment] 2020-06-29 17:49
@Tabgyn Have you checked the NLog InternalLogger ?  https://github.com/NLog/NLog/wiki/Logging-troubleshooting

**Comment by Tabgyn** [comment] 2020-06-29 18:33
Yes

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwConfigExceptions="true"
      internalLogFile="c:\log.txt" internalLogLevel="Trace">
...
```
I don't see errors
[log.txt](https://github.com/NLog/NLog.Web/files/4847374/log.txt)

**Comment by snakefoot** [comment] 2020-06-29 18:44
Guess you have to start debugging, and figure out why NLog fails to extract anything from [InputStream](https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest.inputstream):

https://github.com/NLog/NLog.Web/blob/14ea99e7f263799b6289d1a0849439281aed6a87/src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs#L136-L144

**Closed** 2020-06-29 20:27 UTC
Labels: question

**Comment by snakefoot** [comment] 2022-07-25 10:10
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to explicit call `context.Request.EnableBuffering();` as it is handled by the middleware.
