### ISSUE TITLE
Structured logging of only one object, specifically a string array, only logs the first element

### ISSUE THREAD

**Issue by ceames1** [NLog/NLog.Web#547] opened 2020-04-16 18:47 UTC
**Type** Bug
**NLog.Web/NLog.Web.AspNetCore version**: 4.9.1
**Platform**: .NET Core 3.1
**Current NLog config** not relevant

To show the error, this code:
```c#
int[] intArray= new int[] { 1, 2, 3 };
Logger.LogInformation("My int array: {intArray}", intArray);

string message = "george";
string[] stringArray= new string[] { "tom", "dick", "harry" };
Logger.LogInformation("Hey there, {stringArray}", stringArray);
Logger.LogInformation("Hey there, {stringArray}.  My message is: {myMessage}", stringArray, message);
```

Our logs show:
My int array: 1, 2, 3 ---> as expected.  A single int array logs correctly.
Hey there, tom --->  where are the rest of the elements in the array?
Hey there, tom, dick, harry.  My message is: george --->  adding a second object to structured log makes the string array be logged correctly.  Why?

An unnecessary workaround is to add a .ToList(), so...

```c#
string[] stringArray= new string[] { "tom", "dick", "harry" };
Logger.LogInformation("Hey there, {stringArray}", stringArray.ToList());
```

...will produce the expected results.

**Comment by snakefoot** [comment] 2020-04-16 18:57
That looks indeed as a bug. Will take a look. Thanks for reporting.

**Comment by snakefoot** [comment] 2020-04-16 19:01
The `stringArray` is transformed into a params-array by NetCore / MEL, And just becomes normal parameters like this:

`Logger.LogInformation("Hey there, {stringArray}", "tom", "dick", "harry");`

Because there is only one "hole" then it just picks the first.

**Comment by snakefoot** [comment] 2020-04-16 19:03
Yes it debugs into this method:
```
        public static void LogInformation(this ILogger logger, string message, params object[] args)
        {
            logger.Log(LogLevel.Information, message, args);
        }
```

Where "args" is your string-array.

**Comment by snakefoot** [comment] 2020-04-16 19:05
If I do this, then it also works (not being transformed into params obj):

`_logger.LogInformation("Hey there, {stringArray}", (System.Collections.Generic.IList<string>)stringArray);`

**Comment by snakefoot** [comment] 2020-04-16 19:05
Guess not a bug, but a C#-feature :)

**Comment by snakefoot** [comment] 2020-04-16 19:06
So consider making an extension method for your array that performs cast into `IList<T>`. And make sure to use it in your logging.

**Comment by 304NotModified** [comment] 2020-04-16 19:40
Or cast it as `Object`, e.g. 

```c#
_logger.LogInformation("Hey there, {stringArray}", (object)stringArray);
```
See https://stackoverflow.com/questions/36350/how-to-pass-a-single-object-to-a-params-object

**Comment by ceames1** [comment] 2020-04-16 20:15
So does this explain why the int array works?  I can't "connect those dots" in my head to make sense out of that one yet.

**Comment by snakefoot** [comment] 2020-04-16 20:47
Language feature. Google covariance in csharp. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/


Sent from my Sony Xperia


---- ceames1 wrote ----


So does this explain why the int array works? I can't "connect those dots" in my head to make sense out of that one yet.

**Comment by 304NotModified** [comment] 2020-04-16 21:02
Also nice to read: https://codeblog.jonskeet.uk/2013/06/22/array-covariance-not-just-ugly-but-slow-too/

**Comment by ceames1** [comment] 2020-04-17 00:40
I took a very quick look and think I get it and think it makes sense to me.  I just want to do a little deeper dive into those articles before I completely close the issue, though, if that's okay.  Back in the office bright and early Monday and will get right on this.

Thank you so much for the quick response time!  That was fantastic and super-appreciated!

**Comment by snakefoot** [comment] 2020-04-18 20:14
Closing the issue as resolved

**Closed by snakefoot** 2020-04-18 20:14 UTC
Labels: external
