### ISSUE TITLE
Controller Log does not printed in ubuntu

### ISSUE THREAD

**Issue by guhyeon** [NLog/NLog.Web#288] opened 2018-05-16 14:11 UTC
**Envrironment**
Dev: windows, IIS Express, Visualstudio 2017 community.
Prod: Ubuntu 17.10, Nignx
dotnet core 2.0

**Explain**
At linux ubuntu 17.10, 
 nlog does not prints in controller.

when comment out "loggin.ClearProviders();" in program.cs
it prints all.

**Type** (choose one):
- Bug

**NLog version**: 4.5.4

**NLog.Web/NLog.Web.AspNetCore version**: 4.5.4

**NLog.Extensions.Logging version**: 1.0.2

**Platform**:  .NET Core 2 

**Current NLog config** (xml or C#, if relevant)
Default Config for dotnet core 2

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="logs/internal-nlog.txt">

  <!-- enable asp.net core layout renderers -->
  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file  -->
    <target xsi:type="File" name="allfile" fileName="logs/nlog-all-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}" />

    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="logs/nlog-own-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="allfile" />

    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" maxLevel="Info" final="true" />
    <!-- BlackHole without writeTo -->
    <logger name="*" minlevel="Trace" writeTo="ownFile-web" />
  </rules>
</nlog>

```
In case of a BUG:

- What is the current result?
In ubuntu, only logging works in program.cs.

```
OS                       location                 OK
ubuntu          program.cs              O
ubuntu          HomeController.cs  X
Window        program.cs              O
Window        HomeController.cs  O
```

if comment logging.ClearProviders()
then working well.

- What is the expected result?
It looks like has bugs in ClearProviders().

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
yes but there is no problem.

- Please post full exception details (message, stacktrace, inner exceptions)
No Error message.

- Are there any workarounds? yes/no
yes. It is commenting logging.ClearProviders()

- Is there a version in which it did work? 
- Can you help us by writing an unit test?

```c#
**HomeController.cs
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _context = context;
            _logger = logger;
            logger.LogInformation("HomeController constructor");  //=> not printed in linux.
        }

**Program.cs
    public class Program
    {
        public static void Main(string[] args)
        {
            // NLog: setup the logger first to catch all errors
            var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
            try
            {
                logger.Debug("init main");
                var host = BuildWebHost(args);
                using (var scope = host.Services.CreateScope())
                {
                    var services = scope.ServiceProvider;

                    try
                    {
                        Seeder seeder = new Seeder();
                        seeder.Seed(services, true);
                        //SeedData.Initialize(services);
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex, "An error occurred seeding the DB.");
                    }
                }


                logger.Info("Host Run");
                host.Run();
            }
            catch (Exception ex)
            {
                //NLog: catch setup errors
                logger.Error(ex, "Stopped program because of exception");
                throw;
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                NLog.LogManager.Shutdown();
            }
        }

        public static IWebHost BuildWebHost(string[] args) =>
         WebHost.CreateDefaultBuilder(args)
            .UseUrls("http://localhost:5000")
            .UseStartup<Startup>()
             .ConfigureLogging(logging =>
             {
                 logging.ClearProviders(); //it is commented then working good.
                 logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
             })
            .UseNLog()  // NLog: setup NLog for Dependency injection
            .UseApplicationInsights()
            .Build();
    }

**Comment by 304NotModified** [comment] 2018-05-16 20:29
Thanks for reporting!

it's a bit strange that it works on Windows and not on Linux when `  logging.ClearProviders();` is enabled.

It would be nice if we could compare the internal log on Windows and on Linux. Would it be possible to post them both?

**Comment by guhyeon** [comment] 2018-05-17 11:59
OMG.....
I'm so sorry about reporting this problem as a bug.

I tried to reproduce this problem. but I can't do that again.

Same setting, but It is work very well...

**Comment by 304NotModified** [comment] 2018-05-18 20:16
Glad it has been resolved.

Please feel free to comment if the problem is back again. Closing for now.

**Closed by 304NotModified** 2018-05-18 20:16 UTC
Labels: bug
