### ISSUE TITLE
UseNLog() in 4.5.0-beta01 removes ConsoleLogger from .Net Core

### ISSUE THREAD

**Issue by agentschmitt** [NLog/NLog.Web#199] opened 2017-10-13 16:02 UTC
After updating from NLog.Web.AspNetCore 4.3.1 to 4.5.0-beta01, the ConsoleLogger from .NET does no longer work.
"CreateDefaultBuilder" adds the ConsoleLogger by default, but after i am adding "UseNlog" no messages are logged to console any more.
Does Nlog Registration remove the Loggers already registered?
Maybe this issue is related? "Add option to remove other loggers #192"

This is my Nlog Setup, created as descriped in https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2
```
            var logger = NLogBuilder.ConfigureNLog("NLog.config").GetCurrentClassLogger();

            var hostBuilder = WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseNLog();
```

**Comment by 304NotModified** [comment] 2017-10-13 19:03
Have you check this. We don't remove any logger. Probably the issue is the custom log factory

**Comment by 304NotModified** [comment] 2017-10-13 19:03
Thanks again for reporting!

**Comment by snakefoot** [comment] 2017-10-13 19:55
When using GetCurrentClassLogger() then one is no longer using Microsoft Extension Logging, but writing directly to the NLog-engine, maybe this is the confusing part?

**Comment by 304NotModified** [comment] 2017-10-13 20:13
I found the issue (but not yet how to solve)

in asp.net 2 we register [NLogLoggerFactory](https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/NLogLoggerFactory.cs), instead of [NLogLoggerProvider](https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/NLogLoggerProvider.cs). 

This is a more clean way, but the side-effect is that addConsole is not working

**Comment by 304NotModified** [comment] 2017-10-13 20:53
Dunno how to solve this, because without adding a new Factory, i'm missing some context (the IServiceProvider)

**Comment by 304NotModified** [comment] 2017-10-13 21:44
fixed in beta 2

**Closed** 2017-10-13 21:44 UTC
Labels: bug
