### ISSUE TITLE
System.ArgumentOutOfRangeException in Chinese Path

### ISSUE THREAD

**Issue by syy110112** [NLog/NLog.Web#298] opened 2018-06-29 08:32 UTC
I found when i create a project with Chinese path,the NLog initialize 
will error
`var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();`
Length cannot be less than zero
and i used Mac for .net core 2.0

**Comment by snakefoot** [comment] 2018-06-29 18:41
Duplicate of #237 ? (Try upgrading to the recently released NetCore 2.1)

**Comment by 304NotModified** [comment] 2018-07-05 20:50
I think this is also #237. Please try to upgrade to .NET Core 2.1.

If that won't resolve your problem, please let us know!

**Closed by 304NotModified** 2018-07-05 20:50 UTC

**Comment by syy110112** [comment] 2018-07-07 07:30
it was only released 2.1v yesterday in China，when i upgrade to 2.1v ,it will be ok.
thank you！
